source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'AWSiOSSDKv2', '~> 2.2.2'
pod 'Facebook-iOS-SDK', '~> 3.0'
#pod 'google-plus-ios-sdk'
pod 'FSImageViewer', '~> 3.2'
pod 'APAddressBook'
pod 'TTTAttributedLabel' , '~> 1.10.1'
pod 'JTCalendar'
pod 'SwipeBack', '~> 1.0'
pod 'Stripe'
pod 'Reachability'
pod "youtube-ios-player-helper", "~> 0.1.4"

